/**
 *  Traduce todos los dicionarios de menu al array de idiomas definidos
 */

const ARRNEWLAN = ["en", "ca", "pt", "fr", "it", "de"];

/** Don't touch */
const USER_CODE = Ax.ext.user.getCode();
const DATE_CURRENT = new Ax.util.Date();

ARRNEWLAN.forEach((NEWLANG) => {
  console.log(`-----------------${NEWLANG}-----------------`);
  function translate(data) {
    try {
      return Ax.ext.google.translate.translateText("es", NEWLANG, data) ?? "";
    } catch (err) {
      return "";
    }
  }

  let mRsDetalle = Ax.db.executeQuery(`
       SELECT '${NEWLANG}' locale_tar,
          wic_obj_menu_locale.locale,
          wic_obj_menu_locale.menu_id,
          wic_obj_menu_locale.menu_name
      FROM 
       -- Generated by: DMLSelectFrom
       wic_obj_menu_locale
        WHERE 
        wic_obj_menu_locale.locale = 'es' AND 
        NOT EXISTS (SELECT rowid 
                                   FROM wic_obj_menu_locale t 
                                 WHERE t.menu_id = wic_obj_menu_locale.menu_id
                                       AND t.locale='${NEWLANG}')
    `);

  mRsDetalle.forEach((data) => {
    try {
      Ax.db.beginWork();

      if (data.menu_name) {
        let desc_translate = translate(data.menu_name);
        data.menu_name = desc_translate
          ? desc_translate[0].toUpperCase() + desc_translate.slice(1)
          : "";
      }

      Ax.db.insert("wic_obj_menu_locale", {
        menu_id: data.menu_id,
        locale: NEWLANG,
        menu_name: data.menu_name,
        user_created: USER_CODE,
        user_updated: USER_CODE,
        date_created: DATE_CURRENT,
        date_updated: DATE_CURRENT,
      });

      Ax.db.commitWork();
      console.log("Successfull translating:", data.menu_name);
    } catch (err) {
      console.log("Error translating:", err);
      Ax.db.rollbackWork();
    }
  });
});
